# Generated by Django 4.1.2 on 2022-10-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="task",
            name="done",
            field=models.CharField(
                choices=[("doing", "Doing"), ("done", "Done")], max_length=5
            ),
        ),
    ]
